//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseUpdater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ORMDatabaseUpdater.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/clear&apos; to clear the console..
        /// </summary>
        internal static string Command_Clear_Description {
            get {
                return ResourceManager.GetString("Command_Clear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/exit&apos; to close the application..
        /// </summary>
        internal static string Command_Exit_Description {
            get {
                return ResourceManager.GetString("Command_Exit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/help&apos; to see which actions you can perform..
        /// </summary>
        internal static string Command_Help_Description {
            get {
                return ResourceManager.GetString("Command_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/update all&apos; to update the entire selected database..
        /// </summary>
        internal static string Command_Update_All_Description {
            get {
                return ResourceManager.GetString("Command_Update_All_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter(s) provided for {0}. Type [/help] to see which actions you can perform..
        /// </summary>
        internal static string Command_Update_InvalidParameter {
            get {
                return ResourceManager.GetString("Command_Update_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/update table_name&apos; to update a specific table..
        /// </summary>
        internal static string Command_Update_TableName_Description {
            get {
                return ResourceManager.GetString("Command_Update_TableName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;/help&apos; to see which actions you can perform..
        /// </summary>
        internal static string Help_Description {
            get {
                return ResourceManager.GetString("Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string Select_Database_Format {
            get {
                return ResourceManager.GetString("Select_Database_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a database between 0 and {0}:.
        /// </summary>
        internal static string SelectDatabase_Description {
            get {
                return ResourceManager.GetString("SelectDatabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos; has been selected..
        /// </summary>
        internal static string SelectedDatabase_Description {
            get {
                return ResourceManager.GetString("SelectedDatabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: &apos;{0}&apos; is unknown. Type &apos;/help&apos; to see which actions you can perform..
        /// </summary>
        internal static string UnknownCommend_Description {
            get {
                return ResourceManager.GetString("UnknownCommend_Description", resourceCulture);
            }
        }
    }
}
